# Configuración global mínima
title: "Juan Jesús Ramos Sosa"
description: "SysAdmin & Cybersecurity"
baseurl: "" # Déjalo vacío
url: "https://jesusramos-it.github.io"

# La solución mágica está aquí:
# Le decimos a Jekyll que cargue nuestro CSS personalizado 
# ANTES que el predeterminado de GitHub.
sass:
  style: :compressed
